name: Terraform Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_INPUT: false
  TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_object_id: ${{ secrets.AZURE_OBJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login via OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: environments/DEV

    - name: Terraform Plan
      run: terraform plan -var-file="dev.tfvars" -out=tfplan
      working-directory: environments/DEV

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: environments/DEV